AWSTemplateFormatVersion: '2010-09-09'
Description: Creating AWS ECR Repository

Resources:
  app:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'cicd-project-app'
      EmptyOnDelete: true
      EncryptionConfiguration:
           EncryptionType: AES256
      ImageScanningConfiguration:
           ScanOnPush: false
      ImageTagMutability: MUTABLE
  db:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'cicd-project-db'
      EmptyOnDelete: true
      EncryptionConfiguration:
           EncryptionType: AES256
      ImageScanningConfiguration:
           ScanOnPush: false
      ImageTagMutability: MUTABLE
  web:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'cicd-project-web'
      EmptyOnDelete: true
      EncryptionConfiguration:
           EncryptionType: AES256
      ImageScanningConfiguration:
           ScanOnPush: false
      ImageTagMutability: MUTABLE


Outputs:
  RepositoryURI:
    Description: The URI of the created ECR repository
    Value: !GetAtt app.RepositoryUri
    