AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an AWS EKS Cluster

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to operate in
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key pair to associate with the worker nodes
  NodeGroupName:
    Type: String
    Description: Name of the EKS node group
  NodeInstanceType:
    Description: EC2 instance type for the worker nodes
    Type: String
    Default: t3.micro
    AllowedValues:
    - t3.micro
    - t3.small
    - c7i-flex.large
    - m7i-flex.large
  DesiredCapacity:
    Type: Number
    Description: Desired number of worker nodes
    Default: 2
    MinValue: 1
    MaxValue: 10

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.31"
      Name: !Ref ClusterName
      RoleArn: !ImportValue EKSClusterARN
      ResourcesVpcConfig:
        SecurityGroupIds:
             - !ImportValue EKSSecurityGroupID
        SubnetIds: !Ref SubnetId
        EndpointPublicAccess: true
        EndpointPrivateAccess: false

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      RemoteAccess:
           Ec2SshKey: !Ref KeyName
           SourceSecurityGroups:
                - !ImportValue NodeGroupSecurityGroupID
      CapacityType: ON_DEMAND
      AmiType: AL2_x86_64
      ClusterName: !Ref ClusterName
      NodegroupName: !Ref NodeGroupName
      NodeRole: !ImportValue EKSNodeGroupARN
      Subnets: !Ref SubnetId
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MinSize: 1
        MaxSize: 10
      InstanceTypes:
        - !Ref NodeInstanceType
    DependsOn:
         -  EKSCluster 
  ObservabilityAddon:
    Type: AWS::EKS::Addon
    Properties:
         ClusterName: !Ref ClusterName
         AddonName: "amazon-cloudwatch-observability"
    DependsOn:
         - EKSCluster
         - NodeGroup
         
 